---
- name: debug
  debug:
    msg: "jeste buildbote"
- name: system pkgs install (python, gcc)
  yum:
    name:
      - "python{{ app.value.buildbot_master.configs.python|replace('.','') }}"
      - "python{{ app.value.buildbot_master.configs.python|replace('.','') }}-setuptools"
      - "python{{ app.value.buildbot_master.configs.python|replace('.','') }}-devel"
      - gcc
      - git
      - libselinux-python
  become: true

- name: set app dir value
  set_fact:
    _app_dir: "{{ app.value.buildbot_master.user.home }}/{{ app.key }}"

- block:
    - name: create dir for app
      file:
        path: "{{ _app_dir }}"
        state: directory
        mode: 0755

    - name: create .ssh dir
      file:
        path: "{{app.value.buildbot_master.user.home}}/.ssh"
        state: directory

    - name: generate ssh key
      openssh_keypair:
        path: "{{app.value.buildbot_master.user.home}}/.ssh/id_rsa"
        comment: "{{inventory_hostname}}-{{app.value.buildbot_master.user.user}}"

    - name: install pip
      vars:
        ansible_python_interpreter: "/usr/bin/python{{ app.value.buildbot_master.configs.python }}"
      pip:
        name: "pip"
        state: latest
        virtualenv: "{{ _app_dir }}/venv"
        virtualenv_command: "/usr/bin/python{{ app.value.buildbot_master.configs.python }} -m venv"

    - name: install buildbot master
      vars:
        ansible_python_interpreter: "/usr/bin/python{{ app.value.buildbot_master.configs.python }}"
      pip:
        name: "buildbot[bundle]"
        virtualenv: "{{ _app_dir }}/venv"
        virtualenv_command: "/usr/bin/python{{ app.value.buildbot_master.configs.python }} -m venv"

    - name: create master
      command: "{{ _app_dir }}/venv/bin/buildbot create-master {{ _app_dir }}"
      args:
        creates: "{{ _app_dir }}/state.sqlite"

    ### TODO: find a way to do this without creating files in role!!!
    - name: create userdefined macros heler (always run)
      copy:
        content: "{{ app.value.buildbot_master.configs.configuration.macros  + buildbot_default_macros }}"
        dest: "{{ role_path }}/templates/.macros_helper.j2"
        mode: 0644
      become: false
      check_mode: false
      delegate_to: localhost

    - name: copy master.cfg
      template:
        src: master.cfg
        dest: "{{ _app_dir }}/master.cfg"
        validate: ~/{{ app.key }}/venv/bin/buildbot checkconfig %s
        mode: 0644
      notify:
        - buildbot restart

  become: true
  become_user: "{{ app.value.buildbot_master.user.user }}"

- block:
    - name: copy service
      template:
        src: buildbot-master.service
        dest: "/etc/systemd/system/{{ app.value.buildbot_master.user.user }}_buildbot-master.service"
        mode: 0644
      notify:
        - daemon reload
        - buildbot restart

    - meta: flush_handlers

    - name: start buildbot
      service:
        name: "{{ app.value.buildbot_master.user.user }}_buildbot-master.service"
        state: started
        enabled: true

  become: true
- include_tasks: consul_discovery.yml
