- name: daemon reload
  systemd:
    daemon_reload: yes
    name: "{{app.value.gerrit.user.user}}-gerrit.service"
  become: True

- name: buildbot restart
  service:
    name: "{{app.value['buildbot.master'].user.user}}_buildbot-master"
    state: restarted
  become: True
