- name: daemon reload
  systemd:
    daemon_reload: yes
    name: "{{app.value.buildbot_master.user.user}}_buildbot-master.service"
  become: True

- name: buildbot restart
  service:
    name: "{{app.value.buildbot_master.user.user}}_buildbot-master"
    state: restarted
  become: True
